package at.ac.tuwien.detlef.domain;

import com.dragontek.mygpoclient.feeds.IFeed.IEpisode;

/**
 * Dummy class to display initial test episode content
 * until the actual podcast classes are available.
 */
public class Episode implements IEpisode {

    public static enum State {
        NEW, DOWNLOADED, PLAYED
    }

    private String title;
    private Podcast podcast;
    private Episode.State state;

    public String getTitle() {
        return title;
    }

    public Episode.State getState() {
        return state;
    }

    public void setState(Episode.State state) {
        this.state = state;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Podcast getPodcast() {
        return podcast;
    }

    public void setPodcast(Podcast podcast) {
        this.podcast = podcast;
    }

    /* The following are autogenerated dummy methods. */

    public String getAuthor() {
        // TODO Auto-generated method stub
        return null;
    }

    public String getDescription() {
        // TODO Auto-generated method stub
        return null;
    }

    public IEnclosure getEnclosure() {
        // TODO Auto-generated method stub
        return null;
    }

    public String getGuid() {
        // TODO Auto-generated method stub
        return null;
    }

    public String getLink() {
        // TODO Auto-generated method stub
        return null;
    }

    public long getReleased() {
        // TODO Auto-generated method stub
        return 0;
    }

}
