package net.x4a42.volksempfaenger.feedparser;

public class Enums {
	public static enum Namespace {
		NONE, ATOM, RSS, RSS_CONTENT, UNKNOWN, XHTML, ITUNES
	}

	public static enum Tag {
		UNKNOWN, ATOM_FEED, ATOM_TITLE, ATOM_ENTRY, ATOM_LINK, ATOM_SUMMARY, ATOM_CONTENT, ATOM_PUBLISHED, ATOM_SUBTITLE, RSS_TOPLEVEL, RSS_CHANNEL, RSS_ITEM, RSS_TITLE, RSS_LINK, RSS_DESCRIPTION, RSS_ENCLOSURE, RSS_PUB_DATE, RSS_CONTENT_ENCODED, ATOM_ID, RSS_GUID, RSS_IMAGE, RSS_URL, ATOM_ICON, ITUNES_IMAGE, ITUNES_SUMMARY, ATOM_UPDATED
	}

	public static enum AtomRel {
		ENCLOSURE, ALTERNATE, SELF, UNKNOWN, PAYMENT
	}

	public static enum Mime {
		HTML, XHTML, UNKNOWN
	}

	public static enum GpodderKey {
		TITLE, URL, DESCRIPTION, WEBSITE, SCALED_LOGO_URL, UNKNOWN
	}
}
